name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: anthonymonori/android-ci-image:v2.0.0-rc01
    timeout-minutes: 30
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1

      - name: Generate cache key
        run: ./checksum.sh checksum.txt

      - uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ matrix.java }}-${{ hashFiles('checksum.txt') }}
          restore-keys: ${{ runner.os }}-gradle-${{ matrix.java }}-

      - name: Run Tests
        run: ./gradlew test --stacktrace

      - name: Archive Build Reports
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          retention-days: 7
          name: test-results
          path: build/reports
