name: Release

on:
  workflow_run:
    workflows: ["CI build"]
    types:
      - completed

jobs:
  publish_on_main:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        java: [ '11' ]
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1
      - name: Run Tests
        run: ./gradlew check --stacktrace
      - name: Generate cache key
        run: ./checksum.sh checksum.txt
      - uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ matrix.java }}-${{ hashFiles('checksum.txt') }}
          restore-keys: ${{ runner.os }}-gradle-${{ matrix.java }}-
      - name: Install JDK ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java }}
      - name: Generate
        env:
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          ANDROID_KEYSTORE: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
          ANDROID_KEYSTORE_ALIAS: ${{ secrets.ANDROID_KEYSTORE_ALIAS }}
          ANDROID_KEYSTORE_PRIVATE_KEY_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PRIVATE_KEY_PASSWORD }}
          FIREBASE_SERVICE_ACCOUNT_JSON: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_BASE64 }}
        run:
          echo -n "$FIREBASE_SERVICE_ACCOUNT_JSON" | base64 --decode > ./app/google-services.json
          export GOOGLE_APPLICATION_CREDENTIALS=./app/google-services.json
          echo -n "$ANDROID_KEYSTORE" | base64 --decode > ./app/release.keystore
      - name: Publish
        run: ./gradlew :app:bundleRelease :app:appDistributionUploadRelease --no-build-cache --stacktrace
      - name: Cleanup
        run: rm -f ./app/release.keystore ./app/firebase_google_account.json