name: Release

on:
  workflow_run:
    workflows: [ Build ]
    types:
      - completed

jobs:
  publish_on_main:
    runs-on: ubuntu-latest
    container:
      image: anthonymonori/android-ci-image:v2.0.0-rc01
    timeout-minutes: 30
    env:
      ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
      ANDROID_KEYSTORE_ALIAS: ${{ secrets.ANDROID_KEYSTORE_ALIAS }}
      ANDROID_KEYSTORE_PRIVATE_KEY_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PRIVATE_KEY_PASSWORD }}
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1

      - name: Generate Keystore file
        env:
          ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
        run: echo -n "$ANDROID_KEYSTORE_BASE64" | base64 --decode > ./app/release.keystore

      - name: Publish
        run: ./gradlew :app:bundleRelease :app:appDistributionUploadRelease --no-build-cache --stacktrace

      - name: Cleanup
        run: rm -f ./app/release.keystore ./app/firebase_google_account.json