name: Release

on:
  release:
    types: [created]

jobs:
  publish_release:
    runs-on: ubuntu-latest
    container:
      image: anthonymonori/android-ci-image:v2.0.0-rc01
    timeout-minutes: 30
    env:
      ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
      ANDROID_KEYSTORE_ALIAS: ${{ secrets.ANDROID_KEYSTORE_ALIAS }}
      ANDROID_KEYSTORE_PRIVATE_KEY_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PRIVATE_KEY_PASSWORD }}
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1

      - name: Generate Keystore and Play Service Account file
        env:
          ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
          PLAY_SERVICE_ACCOUNT_JSON: ${{ secrets.PLAY_SERVICE_ACCOUNT_BASE64 }}
        run:
          echo -n "$ANDROID_KEYSTORE_BASE64" | base64 --decode > ./app/release.keystore
          export ANDROID_PUBLISHER_CREDENTIALS=$(echo -n "$PLAY_SERVICE_ACCOUNT_JSON" | base64 --decode)

      - name: Publish
        run: ./gradlew :app:publishReleaseBundle --no-build-cache --stacktrace

      - name: Cleanup
        run:
          rm -f ./app/release.keystore
          unset ANDROID_PUBLISHER_CREDENTIALS